name: Build and Push Docker Image

# Define the events that trigger the workflow
on:
  push:                     # Trigger workflow on pushes to the main branch
    branches:
      - main
  pull_request:             # Trigger workflow on pull requests to the main branch
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: <your-dockerhub-username>/docx-to-pdf:latest
